<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <!-- 配置父 -->
    <parent>
        <groupId>com.lodsve.maven.plugins</groupId>
        <artifactId>lodsve-maven-plugin-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>lodsve-shade-maven-plugin</artifactId>
    <packaging>jar</packaging>
    <name>Lodsve Shade Maven Plugin</name>
    <description>Lodsve Shade Maven Plugin</description>

    <dependencies>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>${maven.shade.plugin.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <properties>
        <main.user.dir>${basedir}/..</main.user.dir>
        <maven.shade.plugin.version>3.0.0</maven.shade.plugin.version>
    </properties>
</project>
